version: '3'
services:
  web_server:
    build: ./static
    container_name: nginx
    ports:
      - "9000:80"
    network_mode: "host"
    depends_on:
        - app
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
        #volumes:
        #- ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    environment:
      FLASK_APP: server
    ports:
      - "5000:5000"
        #command: bash run.sh
    #   volumes:
    # - .:/server
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5000
    depends_on:
      - postgres

